#!/bin/sh

######

# Shinken adds terminal color codes to its' module list.
# Unfortunately, they interfere with scripting and must be
# stripped from Shinken output...
#
decolor() {
    perl -pe 's/\e([^\[\]]|\[.*?[a-zA-Z]|\].*?\a)//g' | \
        col -b 
    }
    
######

SHINKEN_ROOT=${HOME}/Projects/shinken

SHINKEN_MODULES=${SHINKEN_ROOT}/modules

shinken search all | \
    cut -d' ' -f1 | \
    decolor | \
while read module
do
    shinken install --download-only ${module}
    mv /tmp/${module}.tar.gz ${SHINKEN_MODULES}
done
